backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: "src/pages/blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime"}
      - {label: "Vorschaubild", name: "featuredimage", widget: image}
      - {label: "Inhalt", name: "body", widget: "markdown"}