backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: "src/pages/blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Veröffentlichungsdatum", name: "date", widget: "datetime"}
      - {label: "Vorschaubild", name: "featuredimage", widget: image}
      - {label: "Inhalt", name: "body", widget: "markdown"}
  - name: pages
    label: Seiten
    files:
      - file: "src/pages/index.md"
        label: "Vorderseite"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Titel, name: title, widget: string}
          - {label: Kurzbeschreibung, name: blogDescription, widget: string}
      - file: "src/pages/kontakt.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: Titel, name: title, widget: string}
          - {label: "Inhalt", name: "body", widget: "markdown"}
      - file: "src/pages/ich.md"
        label: "Ich"
        name: "ich"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "ich-page"}
          - {label: Titel, name: title, widget: string}
          - {label: "Inhalt", name: "body", widget: "markdown"}
